# This file contains values from Cookiecutter

default_context:
  project_name: "ecdl"
  project_description: "An electronic circuit description language package used to synthesize electrical circuits"
  organization: "girivs82"
  license: "Apache Software License 2.0"
  minimal_python_version: 3.10
  github_name: "girivs82"
  email: "32936671+girivs82@users.noreply.github.com"
  version: "0.1.0"
  line_length: "119"
  create_example_template: "cli"
